//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSCarparking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parking
    {
        public int id { get; set; }
        public string parking_id { get; set; }
        public string parking_name { get; set; }
        public Nullable<double> parking_longitude { get; set; }
        public Nullable<double> parking_latitude { get; set; }
        public Nullable<int> parking_available_slots { get; set; }
        public Nullable<int> town_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<int> slots { get; set; }
        public string price_per_day { get; set; }
    
        public virtual town town { get; set; }
    }
}
